# Generated by Django 2.2.10 on 2021-03-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_status', models.BooleanField(default=True, null=True)),
                ('potential_trade', models.BooleanField(default=False, null=True)),
                ('trade_btc', models.BooleanField(default=False, null=True)),
                ('trade_usd', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
