# Generated by Django 2.2.10 on 2021-04-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_usd', models.CharField(max_length=100, null=True)),
                ('balance_btc', models.CharField(max_length=100, null=True)),
                ('currency3', models.CharField(max_length=100, null=True)),
                ('balance3', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
