# Generated by Django 2.2.10 on 2021-04-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_balance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='percent_chng',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
