# Generated by Django 2.2.10 on 2021-05-05 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210411_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Name')),
                ('passphrase', models.CharField(blank=True, max_length=512, null=True, verbose_name='PassPhrase')),
                ('api_key', models.CharField(blank=True, max_length=512, null=True, verbose_name='API_KEY')),
                ('api_secret', models.CharField(blank=True, max_length=512, null=True, verbose_name='API_SECRET')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='BotConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('symbol', models.CharField(blank=True, max_length=512, null=True, verbose_name='Symbol')),
                ('timeframe', models.CharField(blank=True, max_length=512, null=True, verbose_name='Timeframe')),
                ('price_var', models.FloatField(blank=True, null=True, verbose_name='PriceVar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Portfolio')),
            ],
        ),
    ]
