# Generated by Django 2.2.10 on 2021-05-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_botconfiguration_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='acc_type',
            field=models.CharField(choices=[('LIVE', 'LIVE'), ('DEMO', 'DEMO')], default='LIVE', max_length=512, verbose_name='acc_type'),
        ),
    ]
