# Generated by Django 2.2.10 on 2021-05-07 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_portfolio_acc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Portfolio'),
        ),
    ]
