# Generated by Django 2.2.10 on 2021-05-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_account_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfiguration',
            name='last_action',
            field=models.CharField(default='NAN', max_length=512, verbose_name='LastAction'),
        ),
    ]
