# Generated by Django 2.2.10 on 2021-05-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_botconfiguration_last_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfiguration',
            name='last_price',
            field=models.FloatField(default=-1, verbose_name='PriceVar'),
        ),
    ]
